oca_port/port_addon_pr.py

Always use the full branch reference instead of the local name.

Fix error "Ref '{BRANCH}' did not resolve to an object"

---

oca_port/__init__.py
oca_port/misc.py

This allows to port a module from a development branch (not yet merged in the upstream repository):
```sh
$ oca-port camptocamp/14.0-mig-my_module 15.0 my_module
```
TODO: check how to improve this integration for source+target branches

Able to use '{REMOTE}/{BRANCH}' syntax as source branch

---

oca_port/__init__.py
oca_port/migrate_addon.py
oca_port/misc.py
oca_port/port_addon_pr.py

This change is not backward-compatible.
This feature will store blacklisted PR or module migration in a `./oca-port/blacklist/{MODULE}.json` file (one file per module) and this will be committed in the working branch so this information will be shared with other contributors (PR or module blacklisted won't be listed anymore, but the reason why it was blacklisted will be displayed instead).
Here is a demo of a blacklisted PR with the current changes: https://github.com/OCA/wms/pull/464
fix #4

Automatically commit blacklisted ports

---

pyproject.toml

Requires a recent version of `pip` (> 21.X?) + `setuptools>=64`.

Enable editable install (pip install -e)

---

oca_port/__init__.py
oca_port/migrate_addon.py
oca_port/port_addon_pr.py
oca_port/utils/__init__.py
oca_port/utils/cache.py
oca_port/utils/git.py
oca_port/utils/github.py
oca_port/utils/misc.py
oca_port/utils/storage.py

- Explode `oca_port.misc` to several `oca_port.utils.*` modules
- Put ported commits & PR data in cache
This allows to speed up the time needed by `oca-port` (~50%) to analyse commits to port for a given module if the command already run in the past by doing two things:
- skip commits already ported (no `Commit` objects creation and no check against its sibling on the target branch)
- avoid HTTP requests against GitHub API by caching their results
The user's cache folder used respect the `$XDG_CACHE_HOME` environment variable, and default to `$HOME/.cache/`.
The cache can also be disabled on demand with the `--no-cache` CLI option:
```sh
$ oca-port [...] --no-cache
```

[IMP] Add user's cache (default to ~/.cache/oca-port/)

---

oca_port/port_addon_pr.py

PortAddonPullRequest: use previous branch as base

---

.github/workflows/test.yml
README.md
oca_port/__init__.py
oca_port/exceptions.py
oca_port/migrate_addon.py
oca_port/port_addon_pr.py
oca_port/utils/cache.py
oca_port/utils/git.py
oca_port/utils/github.py
oca_port/utils/misc.py
pyproject.toml
tests/common.py
tests/data/manifest.py
tests/test_app.py

Several things here (see commits):
- Consolidate all parameters and features provided by the tool in a `App` class (used by all subsequent classes to not duplicate parameters everywhere)
- Ability to write scripts using the `oca_port` Python package (and ease the writing of tests! So some basic tests added)
- Different behavior if used as a CLI tool or as a Python package/API (no fancy output in the former)
- If the CLI tool is used with the `--non-interactive` option, 3 exit codes can be returned:
- `0`: all good, nothing to migrate or port (the Git history is the same on the source & target branches)
- `100`: the module could be migrated on the target branch
- `110`: some commits/pull requests could be ported on the target branch for the given module
- New option `--output` to return a …

Make 'oca-port' available as a Python package + JSON output

---

oca_port/cli/pr.py
oca_port/utils/storage.py
pyproject.toml

You can now blacklist PR directly when you know some of them do not need any porting.
This could make you save a lot of time by skipping useless analysis and false positives.

Add PR blacklist

---

README.md

README: how to use `oca-port-pr`

---

README.md
oca_port/__init__.py

It was the case before the merge of #30

Make 'App' class available as `oca_port.App`

---

oca_port/utils/github.py
tests/test_utils_github.py

The PR title is split by words without including special characters (this doesn't include `_`).
Before this change, the term to match against could have been `my_module:`, e.g.:
```sh
$ oca-port 14.0 16.0 stock_warehouse_flow --output=json | jq .
{
"process": "migrate",
"results": {}
}
```
With this change, the term to match become `my_module`:
```sh
$ oca-port 14.0 16.0 stock_warehouse_flow --output=json | jq .
{
"process": "migrate",
"results": {
"existing_pr": {
"url": "https://github.com/OCA/wms/pull/704",
"ref": "OCA/wms#704",
"author": "RodrigoBM",
"title": "[16.0][MIG] stock_warehouse_flow: Migration to 16.0",
"merged_at": "",
"number": 704
}
}
}
```

[FIX] github.search_migration_pr: fix matching of module name in PR title

---

oca_port/app.py
oca_port/migrate_addon.py
oca_port/port_addon_pr.py
tests/test_app.py

Extracted from #33 
Depending on the running mode (CLI, non-interactive, JSON output...) the result of `App.run()` has to be consistent with the user parameters:
- with non-interactive and without output, return a boolean or exception:
- something to migrate/port: `True`
- nothing to do: `False`
- module doesn't exist on source branch: `ValueError`
- with a format output defined, return the expected format, e.g. with JSON:
- something to migrate/port: non-empty JSON document
- nothing to migrate/port: empty JSON document
- module doesn't exist on source branch: `ValueError`
- as CLI: return an exit code (+ text printed on std output):
- something to migrate: 100
- something to port: 110
- nothing to migrate/port: 0
- module doesn't exist on source branch: 1

App: make returned result consistent with output options

---

tests/common.py
tests/test_app.py

- work on a cloned repository to get upstream repo as origin remote
- add a fork remote
- prevent HTTP requests on GitHub API

Improve tests

---

oca_port/port_addon_pr.py
oca_port/tests/common.py
oca_port/tests/test_app.py
oca_port/tests/test_utils_cache.py
oca_port/utils/cache.py
oca_port/utils/git.py

And do not fetch file paths when initializing `Commit` objects, wait for the first access to `Commit.files` or `Commit.paths` attributes to avoid useless IO.
Requesting files modified by a commit is taking quite a lot of time by `git`, especially on big repositories (basically `git show --stat`).
Before this change, the following command is taking about ~2min to execute in `OCA/wms` repository (with others cache already built):
```sh
$ oca-port 14.0 16.0 stock_warehouse_flow --verbose
```
After, it takes ~2s.

utils.git.Commit: leverage user's cache to get commit file paths

---

README.md
oca_port/app.py
oca_port/cli/main.py
oca_port/cli/pr.py
oca_port/migrate_addon.py
oca_port/port_addon_pr.py
oca_port/tests/common.py
oca_port/tests/test_app.py
oca_port/tests/test_utils_cache.py
oca_port/tests/test_utils_misc.py
oca_port/tests/test_utils_session.py
oca_port/utils/__init__.py
oca_port/utils/cache.py
oca_port/utils/git.py
oca_port/utils/misc.py
oca_port/utils/session.py
oca_port/utils/storage.py
pyproject.toml

This is a rework of #33 , and bring breaking changes, both for CLI tool and API if used as a Python package.
Introduce 3 concepts:
* source: source of the comparison
* target: target of the comparison
* destination: where to push the work done
All of them accept git `[remote/]branch` references, so additional info like repository and organization is retrieved from the remote URL.
This is also a preliminary step to support porting from one repo to another (very handy in case of modules moved to different repos).
CLI syntax changed to this:
$ oca-port origin/14.0 origin/16.0 my_module [--destination camptocamp/dev]
A local `dev` branch where commits have already been ported can be resumed this way:
$ oca-port origin/14.0 dev my_module --target-version=16.0 [--destination camptocamp/dev] …

Refactor main arguments + other improvements

---

oca_port/app.py
oca_port/cli/main.py
oca_port/migrate_addon.py
oca_port/port_addon_pr.py
oca_port/tests/common.py
oca_port/utils/git.py

This will allow to use `oca-port` in repositories having modules in subfolders, like `odoo/local-src` as supported by https://github.com/camptocamp/docker-odoo-project.
E.g:
```sh
$ oca-port origin/master origin/18.0 --source-version=14.0 --upstream-org=camptocamp ./odoo/local-src/my_module --verbose --destination sebalix/18.0-mig-my_module
```

[IMP] Migrate/port modules located in subfolder (module path as input instead of module name)

---

oca_port/port_addon_pr.py

Use full PR reference instead of PR number, so the feature can work cross-repo.
Fix #54

PortAddonPullRequest: fix PR blacklisting

---

oca_port/migrate_addon.py

- Before this commit, somehow it results in:
> pkg_resources.DistributionNotFound: The 'odoo-module-migrator' distribution was not found and is required by the application
- Using try...except
- Take this occasion to use `importlib.metadata`, successor of `pkg_resources`

[FIX] replace pkg_resources with importlib.metadata

---

oca_port/port_addon_pr.py
oca_port/tests/common.py
oca_port/tests/test_app.py
oca_port/tests/test_branches_diff.py
oca_port/utils/cache.py
oca_port/utils/git.py

Address issue #21 
PRs that are updating both the analyzed module + other ones (here called 'satellite') were listed by `oca-port`, even if the commits related to the analyzed module were already ported, because contributions on these satellite modules were not (yet) ported.
In the context of the analyzed module, this brings noise and such PR should not be proposed to be ported, but only mentioned.
There are now two kinds of detected PRs:
- the ones that are updating the current analyzed module: they are proposed to the user as "to be ported" as usual
- the ones where only satellite modules/files remain to be ported: such modules are now listed (in verbose mode), and the user invited to run `oca-port` on them.
As such PRs with commits updating only satellite modules are not proposed …

PortAddonPullRequest: reduce noise by filtering PRs to port

---

README.md

As the lib is imported in python in ocaport it need to be installed in the same env so use inject instead of install. Also use --include-deps so it make available the cmd line of odoo-module-migrator
@sebalix

Fix README odoo-module-migrator installation

---

oca_port/port_addon_pr.py

When trying to port commits from a local branch named e.g. 'test', `_get_original_pr` is unable to return any result when it should.
In such case, we request GitHub API on two different base branches:
- the source one (e.g. `master`/`main`, to be compatible with specific repository)
- the source Odoo version (e.g. `18.0`, if working on a specific branch like `test`)

[FIX] PortAddonPullRequest: retrieve original PR based on Odoo Version branch pattern

---

oca_port/utils/github.py

Without this patch, oca-port crash if you have not github cli installed

fix error when gh is not installed

---

oca_port/app.py
oca_port/migrate_addon.py

If an untracked file gets in conflict with a patch, an error will be raised anyway. Up to the user to do some cleanup before re-trying.
Extracted from #74

[IMP] Allow untracked files in repository, like any git command

---

oca_port/port_addon_pr.py

This is currently failing when working on module path like `a/b/{module}`

PortAddonPullRequest: fix `print_satellite_diff()`, use whole rootdir path

---

oca_port/utils/cache.py

Put source and target repository names in cache filenames to avoid wrong cache result with moved modules.
`app.repo_name` cannot be reliable as key to manage cached data. Better to be accurate about the source and target repositories directly in the file name.
As this commit is changing cache storage structure, it will make the existing cache obsolete, so all calls to oca-port will take longer than usual (like any first execution).

[FIX] UserCache: fix cache for modules that were moved to another repo

---

oca_port/utils/git.py
oca_port/utils/github.py

When requesting GH API to found the original PR of a given commit, wrong PR references could be returned, like here:
https://github.com/OCA/wms/commit/3fc53bb2ea9359f658d2c1196bf5321d4b615b1c
PR OCA/wms#31 is the right one, while OCA/wms#980 is unrelated. To workaround this, we check if the commit is part of the PR commits, ensuring the right PR is returned at the end (if any).
It could be that existing user's cache could contain such wrong results, and `oca-port` won't report the expecting PRs/commits to port in such situation. Clearing the cache with `--clear-cache` is then mandatory.

[FIX] utils.github.get_original_pr() and utils.git.check_path_exists()

---

oca_port/app.py
oca_port/cli/main.py
oca_port/migrate_addon.py
oca_port/port_addon_pr.py
oca_port/tests/common.py
oca_port/tests/test_app.py
oca_port/tests/test_utils_git.py
oca_port/utils/cache.py
oca_port/utils/git.py
oca_port/utils/misc.py
oca_port/utils/session.py
pyproject.toml

Different approach than #64 to move/rename a module to address issue #11:
Optional (can be done in a future PR):
Migrate & rename a module at the same time:
```sh
$ oca-port origin/17.0 origin/18.0 stock_packaging_calculator --move-to product_packaging_calculator --dry-run
ℹ️  stock_packaging_calculator can be migrated from 16.0 to 18.0 and moved to product_packaging_calculator
```
<s>
Module already migrated under a different name:
```sh
$ oca-port origin/17.0 origin/18.0 stock_packaging_calculator
ℹ️ stock_packaging_calculator has been renamed product_packaging_calculator in origin/18.0
product_packaging_calculator already exists on origin/18.0, checking PRs to port...
```
</s>

[IMP] Add support for module renaming
